[WIP] - [JENKINS-51856] Bump dependencies to pick up the new milestones
jenkinsci/job-dsl-plugin pull request #1214
Opened 2020-02-05 09:38 UTC by fcojfernandez

### General context
See [JENKINS-51856](https://issues.jenkins-ci.org/browse/JENKINS-51856) and [issue 280](https://github.com/jenkinsci/configuration-as-code-plugin/issues/280)

Before fixing [issue 280](https://github.com/jenkinsci/configuration-as-code-plugin/issues/280), it's needed to add new milestones to Jenkins Core. This is tried in https://github.com/jenkinsci/jenkins/pull/4450. Its downstream PR https://github.com/jenkinsci/configuration-as-code-plugin/pull/1262 is the proposed fix for the race condition. In the initial PR, @casz commented a possible impact in this plugin.
This PR pretends to be a downstream PR of those ones showing how `job-dsl-plugin` would be updated and demonstrating there is no impact.

### What is expected
I've marked the PR as WI since it's a downstream PR. At this point, when I update the dependencies with the new core and the JCasC fix everything seems to be working fine. I've manually tested and found nothing. @casz @timja @oleg-nenashev any help/review here would be more than welcome

CC @daspilker 

### This PR includes
* Update of the baseline to the incremental from https://github.com/jenkinsci/jenkins/pull/4450
   * I don't know why, but I don't see the incremental version for all the artifacts generated for CasC, so I've deployed a SNAPSHOT version (old-school approach). Since it's just a temporary patch, I don't think it's a real issue for now.

2020-02-05 11:34 UTC, fcojfernandez commented
Trying to re-launch CI

2020-02-05 11:56 UTC, casz commented
@fcojfernandez not sure whether gradle supports incrementals 🤔 

Does it build locally?

2020-02-05 12:00 UTC, fcojfernandez commented
> @fcojfernandez not sure whether gradle supports incrementals

I don't think so, that's why I finally deployed timestamped SNAPSHOTs. This PR is not using finally incrementals, but these SNAPSHOTS.
What I'm seeing it's that in local is building, but CI is failing on windows because it's not able to delete the workspace. Any idea regarding this?

2020-07-15 13:42 UTC, daspilker commented
What's the status here? LTS releases 2.222 and 2.235 have been released. How about updating to 2.222.1?

2023-03-20 20:05 UTC, basil requested changes
@fcojfernandez The baseline has been updated on the main branch in #1265. Please either rebase this and complete the PR, or close it.

2023-03-22 00:10 UTC, basil commented
In the absence of a response in the next few days, I intend to close this PR.

2023-03-23 18:41 UTC, basil commented
Unresponsive.

2023-03-23 18:41 UTC, closed without merging