Remove <optional> from config-file-provider dependency
jenkinsci/job-dsl-plugin pull request #1414
Opened 2024-01-08 11:42 UTC by strangelookingnerd

Remove the `optional` flag from the `config-file-provider` dependency.
To my understanding this dependency is directly referenced in `ExecuteDslScripts` as well as `JenkinsDslScriptLoader` and for that reason should *not* be optional.

Resolves https://github.com/jenkinsci/custom-folder-icon-plugin/issues/280

### Testing done

Ran existing tests without any errors.

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

2024-07-24 08:59 UTC, strangelookingnerd commented
@jenkinsci/job-dsl-plugin-developers any chance this can be reviewed, merged & released?

2024-07-24 09:45 UTC, jonesbusy commented
Not a maintainer of `job-dsl-plugin` but it's weird for me to hard depends on the `config-file-provider`

What about https://github.com/jenkinsci/job-dsl-plugin/blob/e6d655dd5b2874f56af8bf4b99a4d622b752bb98/job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/ExecuteDslScripts.java#L611

This check if the plugin is installed

Also here : https://github.com/jenkinsci/job-dsl-plugin/blob/e6d655dd5b2874f56af8bf4b99a4d622b752bb98/job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/JenkinsDslScriptLoader.java#L26

2024-08-27 00:06 UTC, basil requested changes
This plugin seems to comply with https://www.jenkins.io/doc/developer/plugin-development/optional-dependencies/ before this PR.

2024-08-27 06:35 UTC, strangelookingnerd commented
> This plugin seems to comply with https://www.jenkins.io/doc/developer/plugin-development/optional-dependencies/ before this PR.

This is true, however I'd argue that the [ExecuteDslScripts](https://github.com/jenkinsci/job-dsl-plugin/blob/master/job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/ExecuteDslScripts.java) and [JenkinsDslScriptLoader.java](https://github.com/jenkinsci/job-dsl-plugin/blob/master/job-dsl-plugin/src/main/java/javaposse/jobdsl/plugin/JenkinsDslScriptLoader.java) can be considered core functionallities of this plugin. If these fail to load in case the optional dependency is not present, I don't see the point in them being optional.

2024-08-28 07:20 UTC, strangelookingnerd commented
> Based on the `Jenkins.get().getPluginManager().getPlugin("config-file-provider") != null)` guard, they seem like they should load as described in https://www.jenkins.io/doc/developer/plugin-development/optional-dependencies/ -- are you saying that they aren't loading when the optional dependency is not present?

I was under the assumption, yes. However I fail to reproduce the error from https://github.com/jenkinsci/custom-folder-icon-plugin/issues/280 / https://github.com/jenkinsci/maven-hpi-plugin/pull/391

Closing the PR 👍🏼

2024-08-28 07:20 UTC, closed without merging